version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: custom-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
